name: Deploy Preview

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-preview:
    name: Deploy Preview

    runs-on: ubuntu-latest

    steps:
      # -----------------------------------------------------
      # Checkout do projeto
      # -----------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------------------------------------
      # Setup Node
      # -----------------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # -----------------------------------------------------
      # Instala dependências
      # -----------------------------------------------------
      - name: Install dependencies
        run: npm ci

      # -----------------------------------------------------
      # Build do projeto
      # -----------------------------------------------------
      - name: Build project
        run: npm run build

      # -----------------------------------------------------
      # Deploy Vercel Preview
      # -----------------------------------------------------
      - name: Deploy Preview to Vercel
        run: |
          npx vercel deploy \
          --token=${{ secrets.VERCEL_TOKEN }}